CREATE TABLE public.recipes (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    image_url text,
    prep_time integer,
    cook_time integer,
    servings integer DEFAULT 1 NOT NULL,
    category text,
    source text,
    source_url text,
    author text,
    total_cost numeric(10,2),
    cost_per_serving numeric(10,2),
    price_confidence numeric(3,2),
    is_favorite boolean DEFAULT false,
    is_saved boolean DEFAULT true,
    instagram_username text,
    instagram_profile_picture text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'complete'::text
);
