import { Recipe, Ingredient, ShoppingList, ShoppingItem, InventoryItem } from "@/types";

export const demoUser = {
  id: "demo-user-001",
  email: "chef@umami.app",
  user_metadata: {
    full_name: "Alex Chen",
    avatar_url: null,
  },
  created_at: "2025-01-15T08:30:00.000Z",
};

export const demoRecipes: Recipe[] = [
  {
    id: "demo-recipe-1",
    title: "Creamy Garlic Tuscan Salmon",
    description:
      "Pan-seared salmon in a rich, creamy Tuscan sauce with sun-dried tomatoes, spinach, and parmesan. A restaurant-quality dinner ready in 30 minutes.",
    ingredients: [
      { id: "ing-1", name: "Salmon fillets", amount: 4, unit: "pieces", category: "Seafood", emoji: "🐟" },
      { id: "ing-2", name: "Olive oil", amount: 2, unit: "tbsp", category: "Oils", emoji: "🫒" },
      { id: "ing-3", name: "Garlic cloves", amount: 4, unit: "cloves", category: "Produce", emoji: "🧄" },
      { id: "ing-4", name: "Sun-dried tomatoes", amount: 0.5, unit: "cup", category: "Pantry", emoji: "🍅" },
      { id: "ing-5", name: "Heavy cream", amount: 1, unit: "cup", category: "Dairy", emoji: "🥛" },
      { id: "ing-6", name: "Fresh spinach", amount: 2, unit: "cups", category: "Produce", emoji: "🥬" },
      { id: "ing-7", name: "Parmesan cheese", amount: 0.5, unit: "cup", category: "Dairy", emoji: "🧀" },
      { id: "ing-8", name: "Italian seasoning", amount: 1, unit: "tsp", category: "Spices", emoji: "🌿" },
      { id: "ing-9", name: "Salt", amount: 0.5, unit: "tsp", category: "Spices", emoji: "🧂" },
      { id: "ing-10", name: "Black pepper", amount: 0.25, unit: "tsp", category: "Spices", emoji: "⚫" },
    ],
    instructions: [
      "Season salmon fillets with salt, pepper, and Italian seasoning on both sides.",
      "Heat olive oil in a large skillet over medium-high heat. Sear salmon for 4 minutes per side until golden. Remove and set aside.",
      "In the same skillet, add minced garlic and sun-dried tomatoes. Sauté for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Stir in parmesan cheese until melted and smooth.",
      "Add fresh spinach and cook until wilted, about 2 minutes.",
      "Return salmon to the skillet, spoon sauce over the top, and simmer for 2-3 minutes.",
      "Serve immediately over pasta, rice, or with crusty bread.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
    tags: ["Seafood", "Italian", "Quick", "Dinner", "Keto-Friendly"],
    category: "Dinner",
    cuisine: "Italian",
    difficulty: "Medium",
    nutrition: {
      calories: 485,
      protein: "38g",
      carbs: "6g",
      fat: "34g",
      fiber: "1g",
    },
    createdAt: "2025-06-01T12:00:00.000Z",
    updatedAt: "2025-06-15T09:30:00.000Z",
    isFavorite: true,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-2",
    title: "Thai Green Curry with Chicken",
    description:
      "A fragrant and spicy Thai green curry loaded with tender chicken, bamboo shoots, bell peppers, and fresh Thai basil in a coconut milk base.",
    ingredients: [
      { id: "ing-11", name: "Chicken thighs", amount: 600, unit: "g", category: "Meat", emoji: "🍗" },
      { id: "ing-12", name: "Green curry paste", amount: 3, unit: "tbsp", category: "Condiments", emoji: "🌶️" },
      { id: "ing-13", name: "Coconut milk", amount: 400, unit: "ml", category: "Canned Goods", emoji: "🥥" },
      { id: "ing-14", name: "Bamboo shoots", amount: 1, unit: "can", category: "Canned Goods", emoji: "🎋" },
      { id: "ing-15", name: "Red bell pepper", amount: 1, unit: "piece", category: "Produce", emoji: "🫑" },
      { id: "ing-16", name: "Fish sauce", amount: 2, unit: "tbsp", category: "Condiments", emoji: "🐟" },
      { id: "ing-17", name: "Brown sugar", amount: 1, unit: "tbsp", category: "Baking", emoji: "🍬" },
      { id: "ing-18", name: "Thai basil leaves", amount: 0.5, unit: "cup", category: "Produce", emoji: "🌿" },
      { id: "ing-19", name: "Jasmine rice", amount: 2, unit: "cups", category: "Grains", emoji: "🍚" },
      { id: "ing-20", name: "Lime", amount: 1, unit: "piece", category: "Produce", emoji: "🍋" },
    ],
    instructions: [
      "Cut chicken thighs into bite-sized pieces. Slice bell pepper into thin strips.",
      "In a large wok or pot, heat a splash of coconut milk over high heat. Add green curry paste and fry for 1-2 minutes until fragrant.",
      "Add chicken pieces and stir-fry until sealed on the outside, about 3 minutes.",
      "Pour in the remaining coconut milk, bamboo shoots, and bell pepper. Bring to a simmer.",
      "Season with fish sauce and brown sugar. Simmer for 15 minutes until chicken is cooked through.",
      "Stir in Thai basil leaves and remove from heat.",
      "Serve over steamed jasmine rice with a lime wedge on the side.",
    ],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
    tags: ["Thai", "Curry", "Spicy", "Dinner", "Asian"],
    category: "Dinner",
    cuisine: "Thai",
    difficulty: "Medium",
    nutrition: {
      calories: 520,
      protein: "32g",
      carbs: "45g",
      fat: "28g",
      fiber: "4g",
    },
    createdAt: "2025-05-20T14:00:00.000Z",
    updatedAt: "2025-06-10T11:00:00.000Z",
    isFavorite: true,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-3",
    title: "Classic Margherita Pizza",
    description:
      "Authentic Neapolitan-style Margherita pizza with San Marzano tomato sauce, fresh mozzarella, basil, and a perfectly charred thin crust.",
    ingredients: [
      { id: "ing-21", name: "Pizza dough", amount: 1, unit: "lb", category: "Bakery", emoji: "🍞" },
      { id: "ing-22", name: "San Marzano tomatoes", amount: 1, unit: "can", category: "Canned Goods", emoji: "🍅" },
      { id: "ing-23", name: "Fresh mozzarella", amount: 8, unit: "oz", category: "Dairy", emoji: "🧀" },
      { id: "ing-24", name: "Fresh basil leaves", amount: 10, unit: "leaves", category: "Produce", emoji: "🌿" },
      { id: "ing-25", name: "Extra virgin olive oil", amount: 2, unit: "tbsp", category: "Oils", emoji: "🫒" },
      { id: "ing-26", name: "Garlic", amount: 2, unit: "cloves", category: "Produce", emoji: "🧄" },
      { id: "ing-27", name: "Sea salt", amount: 1, unit: "tsp", category: "Spices", emoji: "🧂" },
      { id: "ing-28", name: "Red pepper flakes", amount: 0.5, unit: "tsp", category: "Spices", emoji: "🌶️" },
    ],
    instructions: [
      "Preheat oven to 500°F (260°C) with a pizza stone or inverted baking sheet inside for at least 30 minutes.",
      "Crush San Marzano tomatoes by hand, mix with minced garlic, salt, and a drizzle of olive oil for the sauce.",
      "Stretch pizza dough on a floured surface into a 12-inch round. Don't use a rolling pin - use your hands.",
      "Spread a thin layer of tomato sauce, leaving a 1-inch border for the crust.",
      "Tear mozzarella into pieces and distribute evenly over the sauce.",
      "Slide pizza onto the hot stone and bake for 8-10 minutes until crust is golden and cheese is bubbly.",
      "Remove from oven, scatter fresh basil leaves, drizzle with olive oil, and sprinkle red pepper flakes.",
    ],
    prepTime: 20,
    cookTime: 10,
    servings: 2,
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
    tags: ["Italian", "Pizza", "Vegetarian", "Quick", "Classic"],
    category: "Dinner",
    cuisine: "Italian",
    difficulty: "Medium",
    nutrition: {
      calories: 650,
      protein: "26g",
      carbs: "72g",
      fat: "28g",
      fiber: "3g",
    },
    createdAt: "2025-06-05T10:00:00.000Z",
    updatedAt: "2025-06-05T10:00:00.000Z",
    isFavorite: false,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-4",
    title: "Avocado Toast with Poached Eggs",
    description:
      "The ultimate brunch staple: perfectly poached eggs on sourdough with smashed avocado, cherry tomatoes, and a sprinkle of everything bagel seasoning.",
    ingredients: [
      { id: "ing-29", name: "Sourdough bread", amount: 2, unit: "slices", category: "Bakery", emoji: "🍞" },
      { id: "ing-30", name: "Avocado", amount: 1, unit: "piece", category: "Produce", emoji: "🥑" },
      { id: "ing-31", name: "Eggs", amount: 2, unit: "pieces", category: "Dairy", emoji: "🥚" },
      { id: "ing-32", name: "Cherry tomatoes", amount: 6, unit: "pieces", category: "Produce", emoji: "🍅" },
      { id: "ing-33", name: "Lemon juice", amount: 1, unit: "tsp", category: "Produce", emoji: "🍋" },
      { id: "ing-34", name: "Everything bagel seasoning", amount: 1, unit: "tsp", category: "Spices", emoji: "✨" },
      { id: "ing-35", name: "Red pepper flakes", amount: 0.25, unit: "tsp", category: "Spices", emoji: "🌶️" },
      { id: "ing-36", name: "White vinegar", amount: 1, unit: "tbsp", category: "Condiments", emoji: "🍶" },
    ],
    instructions: [
      "Toast sourdough bread slices until golden and crisp.",
      "Cut avocado in half, remove pit, scoop into a bowl. Add lemon juice, salt, and pepper. Mash with a fork.",
      "Bring a pot of water to a gentle simmer. Add white vinegar. Create a whirlpool with a spoon.",
      "Crack each egg into a small bowl, then gently slide into the whirlpool. Poach for 3-4 minutes.",
      "Spread mashed avocado on toast. Top with poached eggs.",
      "Halve cherry tomatoes and scatter around. Sprinkle with everything bagel seasoning and red pepper flakes.",
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
    tags: ["Breakfast", "Brunch", "Healthy", "Quick", "Vegetarian"],
    category: "Breakfast",
    cuisine: "American",
    difficulty: "Easy",
    nutrition: {
      calories: 420,
      protein: "18g",
      carbs: "38g",
      fat: "22g",
      fiber: "10g",
    },
    createdAt: "2025-06-10T08:00:00.000Z",
    updatedAt: "2025-06-10T08:00:00.000Z",
    isFavorite: true,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-5",
    title: "Korean Bibimbap Bowl",
    description:
      "A vibrant Korean mixed rice bowl with sautéed vegetables, ground beef bulgogi, a fried egg, and spicy gochujang sauce.",
    ingredients: [
      { id: "ing-37", name: "Steamed rice", amount: 2, unit: "cups", category: "Grains", emoji: "🍚" },
      { id: "ing-38", name: "Ground beef", amount: 200, unit: "g", category: "Meat", emoji: "🥩" },
      { id: "ing-39", name: "Spinach", amount: 2, unit: "cups", category: "Produce", emoji: "🥬" },
      { id: "ing-40", name: "Carrots", amount: 1, unit: "piece", category: "Produce", emoji: "🥕" },
      { id: "ing-41", name: "Zucchini", amount: 1, unit: "piece", category: "Produce", emoji: "🥒" },
      { id: "ing-42", name: "Shiitake mushrooms", amount: 4, unit: "pieces", category: "Produce", emoji: "🍄" },
      { id: "ing-43", name: "Eggs", amount: 2, unit: "pieces", category: "Dairy", emoji: "🥚" },
      { id: "ing-44", name: "Gochujang paste", amount: 2, unit: "tbsp", category: "Condiments", emoji: "🌶️" },
      { id: "ing-45", name: "Soy sauce", amount: 2, unit: "tbsp", category: "Condiments", emoji: "🫘" },
      { id: "ing-46", name: "Sesame oil", amount: 1, unit: "tbsp", category: "Oils", emoji: "🫗" },
    ],
    instructions: [
      "Julienne carrots and zucchini into thin matchsticks. Slice shiitake mushrooms.",
      "Sauté each vegetable separately in a bit of sesame oil with a pinch of salt. Set aside.",
      "Season ground beef with soy sauce, sesame oil, and a bit of gochujang. Cook in a hot skillet until browned.",
      "Blanch spinach in boiling water for 30 seconds, drain, and squeeze out excess water. Season with sesame oil.",
      "Fry eggs sunny-side up in a non-stick pan.",
      "Assemble bowls: place rice in the center, arrange vegetables and beef around in sections. Top with fried egg.",
      "Serve with extra gochujang on the side. Mix everything together before eating!",
    ],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    imageUrl: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800",
    tags: ["Korean", "Asian", "Bowl", "Dinner", "Healthy"],
    category: "Dinner",
    cuisine: "Korean",
    difficulty: "Medium",
    nutrition: {
      calories: 580,
      protein: "30g",
      carbs: "68g",
      fat: "22g",
      fiber: "7g",
    },
    createdAt: "2025-05-28T18:00:00.000Z",
    updatedAt: "2025-06-12T15:00:00.000Z",
    isFavorite: false,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-6",
    title: "Mango Lassi Smoothie Bowl",
    description:
      "A refreshing and creamy mango lassi-inspired smoothie bowl topped with granola, coconut flakes, fresh berries, and a drizzle of honey.",
    ingredients: [
      { id: "ing-47", name: "Ripe mango", amount: 1, unit: "piece", category: "Produce", emoji: "🥭" },
      { id: "ing-48", name: "Greek yogurt", amount: 1, unit: "cup", category: "Dairy", emoji: "🥛" },
      { id: "ing-49", name: "Milk", amount: 0.5, unit: "cup", category: "Dairy", emoji: "🥛" },
      { id: "ing-50", name: "Honey", amount: 2, unit: "tbsp", category: "Condiments", emoji: "🍯" },
      { id: "ing-51", name: "Cardamom powder", amount: 0.25, unit: "tsp", category: "Spices", emoji: "🌿" },
      { id: "ing-52", name: "Granola", amount: 0.25, unit: "cup", category: "Breakfast", emoji: "🥣" },
      { id: "ing-53", name: "Coconut flakes", amount: 2, unit: "tbsp", category: "Baking", emoji: "🥥" },
      { id: "ing-54", name: "Mixed berries", amount: 0.5, unit: "cup", category: "Produce", emoji: "🫐" },
      { id: "ing-55", name: "Chia seeds", amount: 1, unit: "tbsp", category: "Health", emoji: "🌱" },
    ],
    instructions: [
      "Peel and dice the mango. Reserve a few slices for topping.",
      "In a blender, combine mango, Greek yogurt, milk, honey, and cardamom. Blend until thick and creamy.",
      "Pour into a bowl. The consistency should be thicker than a drinkable smoothie.",
      "Arrange granola, coconut flakes, mixed berries, reserved mango, and chia seeds on top in neat rows.",
      "Drizzle with extra honey and serve immediately with a spoon.",
    ],
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    tags: ["Breakfast", "Smoothie", "Indian", "Healthy", "No-Cook"],
    category: "Breakfast",
    cuisine: "Indian",
    difficulty: "Easy",
    nutrition: {
      calories: 380,
      protein: "14g",
      carbs: "58g",
      fat: "12g",
      fiber: "8g",
    },
    createdAt: "2025-06-14T07:00:00.000Z",
    updatedAt: "2025-06-14T07:00:00.000Z",
    isFavorite: true,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-7",
    title: "One-Pan Lemon Herb Chicken",
    description:
      "Juicy roasted chicken thighs with crispy potatoes, caramelized lemons, and fresh herbs — all made in one pan for easy cleanup.",
    ingredients: [
      { id: "ing-56", name: "Chicken thighs", amount: 6, unit: "pieces", category: "Meat", emoji: "🍗" },
      { id: "ing-57", name: "Baby potatoes", amount: 500, unit: "g", category: "Produce", emoji: "🥔" },
      { id: "ing-58", name: "Lemons", amount: 2, unit: "pieces", category: "Produce", emoji: "🍋" },
      { id: "ing-59", name: "Fresh rosemary", amount: 3, unit: "sprigs", category: "Produce", emoji: "🌿" },
      { id: "ing-60", name: "Fresh thyme", amount: 4, unit: "sprigs", category: "Produce", emoji: "🌱" },
      { id: "ing-61", name: "Garlic", amount: 6, unit: "cloves", category: "Produce", emoji: "🧄" },
      { id: "ing-62", name: "Olive oil", amount: 3, unit: "tbsp", category: "Oils", emoji: "🫒" },
      { id: "ing-63", name: "Dijon mustard", amount: 1, unit: "tbsp", category: "Condiments", emoji: "🫙" },
      { id: "ing-64", name: "Salt", amount: 1, unit: "tsp", category: "Spices", emoji: "🧂" },
      { id: "ing-65", name: "Black pepper", amount: 0.5, unit: "tsp", category: "Spices", emoji: "⚫" },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Halve baby potatoes and slice one lemon into thin rounds. Leave garlic cloves whole in their skins.",
      "In a large bowl, whisk olive oil, Dijon mustard, juice of the second lemon, salt, and pepper.",
      "Add chicken thighs, potatoes, lemon slices, garlic, rosemary, and thyme. Toss everything to coat.",
      "Arrange on a large baking sheet in a single layer. Chicken skin-side up.",
      "Roast for 35-40 minutes until chicken is golden and reaches 165°F internal temperature.",
      "Let rest 5 minutes before serving. Spoon pan juices over everything.",
    ],
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800",
    tags: ["Chicken", "One-Pan", "Dinner", "Meal Prep", "Gluten-Free"],
    category: "Dinner",
    cuisine: "Mediterranean",
    difficulty: "Easy",
    nutrition: {
      calories: 450,
      protein: "35g",
      carbs: "28g",
      fat: "24g",
      fiber: "3g",
    },
    createdAt: "2025-06-08T17:00:00.000Z",
    updatedAt: "2025-06-08T17:00:00.000Z",
    isFavorite: false,
    userId: "demo-user-001",
  },
  {
    id: "demo-recipe-8",
    title: "Dark Chocolate Lava Cake",
    description:
      "Rich, indulgent individual chocolate cakes with a molten center that flows out when you break through the perfectly baked exterior.",
    ingredients: [
      { id: "ing-66", name: "Dark chocolate (70%)", amount: 200, unit: "g", category: "Baking", emoji: "🍫" },
      { id: "ing-67", name: "Unsalted butter", amount: 0.5, unit: "cup", category: "Dairy", emoji: "🧈" },
      { id: "ing-68", name: "Powdered sugar", amount: 1, unit: "cup", category: "Baking", emoji: "🍬" },
      { id: "ing-69", name: "Eggs", amount: 2, unit: "pieces", category: "Dairy", emoji: "🥚" },
      { id: "ing-70", name: "Egg yolks", amount: 2, unit: "pieces", category: "Dairy", emoji: "🥚" },
      { id: "ing-71", name: "All-purpose flour", amount: 6, unit: "tbsp", category: "Baking", emoji: "🌾" },
      { id: "ing-72", name: "Vanilla extract", amount: 1, unit: "tsp", category: "Baking", emoji: "🌼" },
      { id: "ing-73", name: "Cocoa powder", amount: 1, unit: "tbsp", category: "Baking", emoji: "🤎" },
      { id: "ing-74", name: "Sea salt", amount: 0.25, unit: "tsp", category: "Spices", emoji: "🧂" },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Grease four 6-oz ramekins with butter and dust with cocoa powder.",
      "Melt dark chocolate and butter together in a double boiler or microwave in 30-second bursts. Stir until smooth.",
      "Whisk in powdered sugar until well combined and slightly cooled.",
      "Add eggs and egg yolks one at a time, whisking well after each addition. Stir in vanilla extract.",
      "Fold in flour and sea salt until just combined. Do not overmix.",
      "Divide batter evenly among prepared ramekins. Place on a baking sheet.",
      "Bake for 12-14 minutes until edges are firm but center is soft and jiggly.",
      "Let cool for 1 minute, then run a knife around the edge. Invert onto a plate. Dust with powdered sugar and serve immediately.",
    ],
    prepTime: 15,
    cookTime: 14,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800",
    tags: ["Dessert", "Chocolate", "Baking", "Special Occasion"],
    category: "Dessert",
    cuisine: "French",
    difficulty: "Hard",
    nutrition: {
      calories: 520,
      protein: "8g",
      carbs: "56g",
      fat: "32g",
      fiber: "4g",
    },
    createdAt: "2025-06-12T20:00:00.000Z",
    updatedAt: "2025-06-12T20:00:00.000Z",
    isFavorite: true,
    userId: "demo-user-001",
  },
];

export const demoShoppingLists: ShoppingList[] = [
  {
    id: "demo-list-1",
    user_id: "demo-user-001",
    name: "Weekly Groceries",
    created_at: "2025-06-20T09:00:00.000Z",
    updated_at: "2025-06-20T09:00:00.000Z",
  },
  {
    id: "demo-list-2",
    user_id: "demo-user-001",
    name: "Dinner Party",
    created_at: "2025-06-18T14:00:00.000Z",
    updated_at: "2025-06-19T10:00:00.000Z",
  },
];

export const demoShoppingItems: ShoppingItem[] = [
  {
    id: "si-1",
    shopping_list_id: "demo-list-1",
    name: "Salmon fillets",
    quantity: "4",
    unit: "pieces",
    category: "Seafood",
    checked: false,
    created_at: "2025-06-20T09:01:00.000Z",
    updated_at: "2025-06-20T09:01:00.000Z",
  },
  {
    id: "si-2",
    shopping_list_id: "demo-list-1",
    name: "Heavy cream",
    quantity: "1",
    unit: "cup",
    category: "Dairy",
    checked: true,
    created_at: "2025-06-20T09:01:00.000Z",
    updated_at: "2025-06-20T15:30:00.000Z",
  },
  {
    id: "si-3",
    shopping_list_id: "demo-list-1",
    name: "Fresh spinach",
    quantity: "2",
    unit: "bags",
    category: "Produce",
    checked: false,
    created_at: "2025-06-20T09:01:00.000Z",
    updated_at: "2025-06-20T09:01:00.000Z",
  },
  {
    id: "si-4",
    shopping_list_id: "demo-list-1",
    name: "Chicken thighs",
    quantity: "600",
    unit: "g",
    category: "Meat",
    checked: true,
    created_at: "2025-06-20T09:02:00.000Z",
    updated_at: "2025-06-20T16:00:00.000Z",
  },
  {
    id: "si-5",
    shopping_list_id: "demo-list-1",
    name: "Coconut milk",
    quantity: "2",
    unit: "cans",
    category: "Canned Goods",
    checked: false,
    created_at: "2025-06-20T09:02:00.000Z",
    updated_at: "2025-06-20T09:02:00.000Z",
  },
  {
    id: "si-6",
    shopping_list_id: "demo-list-1",
    name: "Avocados",
    quantity: "3",
    unit: "pieces",
    category: "Produce",
    checked: false,
    created_at: "2025-06-20T09:03:00.000Z",
    updated_at: "2025-06-20T09:03:00.000Z",
  },
  {
    id: "si-7",
    shopping_list_id: "demo-list-1",
    name: "Eggs",
    quantity: "12",
    unit: "pieces",
    category: "Dairy",
    checked: false,
    created_at: "2025-06-20T09:03:00.000Z",
    updated_at: "2025-06-20T09:03:00.000Z",
  },
  {
    id: "si-8",
    shopping_list_id: "demo-list-2",
    name: "Dark chocolate (70%)",
    quantity: "200",
    unit: "g",
    category: "Baking",
    checked: false,
    created_at: "2025-06-18T14:00:00.000Z",
    updated_at: "2025-06-18T14:00:00.000Z",
    recipe_id: "demo-recipe-8",
  },
  {
    id: "si-9",
    shopping_list_id: "demo-list-2",
    name: "Fresh mozzarella",
    quantity: "8",
    unit: "oz",
    category: "Dairy",
    checked: true,
    created_at: "2025-06-18T14:01:00.000Z",
    updated_at: "2025-06-19T10:00:00.000Z",
    recipe_id: "demo-recipe-3",
  },
  {
    id: "si-10",
    shopping_list_id: "demo-list-2",
    name: "San Marzano tomatoes",
    quantity: "1",
    unit: "can",
    category: "Canned Goods",
    checked: false,
    created_at: "2025-06-18T14:01:00.000Z",
    updated_at: "2025-06-18T14:01:00.000Z",
    recipe_id: "demo-recipe-3",
  },
  {
    id: "si-11",
    shopping_list_id: "demo-list-2",
    name: "Fresh basil",
    quantity: "2",
    unit: "bunches",
    category: "Produce",
    checked: false,
    created_at: "2025-06-18T14:02:00.000Z",
    updated_at: "2025-06-18T14:02:00.000Z",
  },
];

export const demoInventoryItems: InventoryItem[] = [
  {
    id: "inv-1",
    user_id: "demo-user-001",
    name: "Olive oil",
    quantity: "750",
    unit: "ml",
    category: "Oils",
    added_date: "2025-06-01T00:00:00.000Z",
    created_at: "2025-06-01T10:00:00.000Z",
    updated_at: "2025-06-01T10:00:00.000Z",
  },
  {
    id: "inv-2",
    user_id: "demo-user-001",
    name: "Soy sauce",
    quantity: "500",
    unit: "ml",
    category: "Condiments",
    added_date: "2025-05-15T00:00:00.000Z",
    created_at: "2025-05-15T10:00:00.000Z",
    updated_at: "2025-05-15T10:00:00.000Z",
  },
  {
    id: "inv-3",
    user_id: "demo-user-001",
    name: "Jasmine rice",
    quantity: "2",
    unit: "kg",
    category: "Grains",
    added_date: "2025-06-05T00:00:00.000Z",
    created_at: "2025-06-05T10:00:00.000Z",
    updated_at: "2025-06-05T10:00:00.000Z",
  },
  {
    id: "inv-4",
    user_id: "demo-user-001",
    name: "All-purpose flour",
    quantity: "1.5",
    unit: "kg",
    category: "Baking",
    added_date: "2025-05-28T00:00:00.000Z",
    created_at: "2025-05-28T10:00:00.000Z",
    updated_at: "2025-05-28T10:00:00.000Z",
  },
  {
    id: "inv-5",
    user_id: "demo-user-001",
    name: "Garlic",
    quantity: "3",
    unit: "heads",
    category: "Produce",
    added_date: "2025-06-18T00:00:00.000Z",
    expiration_date: "2025-07-02T00:00:00.000Z",
    created_at: "2025-06-18T10:00:00.000Z",
    updated_at: "2025-06-18T10:00:00.000Z",
  },
  {
    id: "inv-6",
    user_id: "demo-user-001",
    name: "Parmesan cheese",
    quantity: "200",
    unit: "g",
    category: "Dairy",
    added_date: "2025-06-15T00:00:00.000Z",
    expiration_date: "2025-07-15T00:00:00.000Z",
    created_at: "2025-06-15T10:00:00.000Z",
    updated_at: "2025-06-15T10:00:00.000Z",
  },
  {
    id: "inv-7",
    user_id: "demo-user-001",
    name: "Gochujang paste",
    quantity: "500",
    unit: "g",
    category: "Condiments",
    added_date: "2025-06-10T00:00:00.000Z",
    expiration_date: "2026-01-01T00:00:00.000Z",
    created_at: "2025-06-10T10:00:00.000Z",
    updated_at: "2025-06-10T10:00:00.000Z",
  },
  {
    id: "inv-8",
    user_id: "demo-user-001",
    name: "Honey",
    quantity: "340",
    unit: "g",
    category: "Condiments",
    added_date: "2025-04-20T00:00:00.000Z",
    expiration_date: "2026-04-20T00:00:00.000Z",
    created_at: "2025-04-20T10:00:00.000Z",
    updated_at: "2025-04-20T10:00:00.000Z",
  },
];
